# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tianwei.ui'
#
# Created: Mon Oct 24 11:42:06 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(517, 731)
        Form.setMaximumSize(QtCore.QSize(517, 731))
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "配置主界面", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_7 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_6 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TeXGyreBonum"))
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setText(QtGui.QApplication.translate("Form", "网络直接获取", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_9.addWidget(self.label_6)
        self.label_listenState = QtGui.QLabel(Form)
        self.label_listenState.setText(_fromUtf8(""))
        self.label_listenState.setObjectName(_fromUtf8("label_listenState"))
        self.horizontalLayout_9.addWidget(self.label_listenState)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(Form)
        self.label.setText(QtGui.QApplication.translate("Form", "网卡输入", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_eth0 = QtGui.QLineEdit(Form)
        self.lineEdit_eth0.setText(QtGui.QApplication.translate("Form", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_eth0.setObjectName(_fromUtf8("lineEdit_eth0"))
        self.horizontalLayout.addWidget(self.lineEdit_eth0)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setText(QtGui.QApplication.translate("Form", "规则表达式过滤", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_ruleListen = QtGui.QLineEdit(Form)
        self.lineEdit_ruleListen.setObjectName(_fromUtf8("lineEdit_ruleListen"))
        self.horizontalLayout_3.addWidget(self.lineEdit_ruleListen)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setText(QtGui.QApplication.translate("Form", "字符串过滤", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_keyWordListen = QtGui.QLineEdit(Form)
        self.lineEdit_keyWordListen.setObjectName(_fromUtf8("lineEdit_keyWordListen"))
        self.horizontalLayout_4.addWidget(self.lineEdit_keyWordListen)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btn_onlyListen = QtGui.QPushButton(Form)
        self.btn_onlyListen.setText(QtGui.QApplication.translate("Form", "仅监听数据", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_onlyListen.setObjectName(_fromUtf8("btn_onlyListen"))
        self.horizontalLayout_5.addWidget(self.btn_onlyListen)
        self.btn_stopListen = QtGui.QPushButton(Form)
        self.btn_stopListen.setText(QtGui.QApplication.translate("Form", "停止监听", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_stopListen.setObjectName(_fromUtf8("btn_stopListen"))
        self.horizontalLayout_5.addWidget(self.btn_stopListen)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_10 = QtGui.QLabel(Form)
        self.label_10.setText(QtGui.QApplication.translate("Form", "注: 1.网卡输入项，终端下输入ifconfig，输出的网卡名称，如eht0等", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setText(QtGui.QApplication.translate("Form", "    2.规则表达式输入端口,IP,协议等信息", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setText(QtGui.QApplication.translate("Form", "    3.字符串过滤输入过滤字符串的正则表达式", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setText(QtGui.QApplication.translate("Form", "    4.监听的数据包保存到\"./pcap_self\"文件夹下", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_3.addWidget(self.label_8)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.line_3 = QtGui.QFrame(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_3.setFont(font)
        self.line_3.setFrameShadow(QtGui.QFrame.Plain)
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_7.addWidget(self.line_3)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_5 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TeXGyreBonum"))
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setText(QtGui.QApplication.translate("Form", "本地文件选择", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_10.addWidget(self.label_5)
        self.label_processState = QtGui.QLabel(Form)
        self.label_processState.setText(_fromUtf8(""))
        self.label_processState.setObjectName(_fromUtf8("label_processState"))
        self.horizontalLayout_10.addWidget(self.label_processState)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setText(QtGui.QApplication.translate("Form", "规则表达式过滤", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_6.addWidget(self.label_11)
        self.lineEdit_ruleLocal = QtGui.QLineEdit(Form)
        self.lineEdit_ruleLocal.setObjectName(_fromUtf8("lineEdit_ruleLocal"))
        self.horizontalLayout_6.addWidget(self.lineEdit_ruleLocal)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_12 = QtGui.QLabel(Form)
        self.label_12.setText(QtGui.QApplication.translate("Form", "字符串过滤", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_7.addWidget(self.label_12)
        self.lineEdit_KeyWordLocal = QtGui.QLineEdit(Form)
        self.lineEdit_KeyWordLocal.setObjectName(_fromUtf8("lineEdit_KeyWordLocal"))
        self.horizontalLayout_7.addWidget(self.lineEdit_KeyWordLocal)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.btn_selectFile = QtGui.QPushButton(Form)
        self.btn_selectFile.setText(QtGui.QApplication.translate("Form", "选择文件", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_selectFile.setObjectName(_fromUtf8("btn_selectFile"))
        self.horizontalLayout_8.addWidget(self.btn_selectFile)
        self.btn_clearSelectedFile = QtGui.QPushButton(Form)
        self.btn_clearSelectedFile.setText(QtGui.QApplication.translate("Form", "清除选择", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clearSelectedFile.setObjectName(_fromUtf8("btn_clearSelectedFile"))
        self.horizontalLayout_8.addWidget(self.btn_clearSelectedFile)
        self.btn_filtertoDB = QtGui.QPushButton(Form)
        self.btn_filtertoDB.setText(QtGui.QApplication.translate("Form", "过滤并存储到数据库", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_filtertoDB.setObjectName(_fromUtf8("btn_filtertoDB"))
        self.horizontalLayout_8.addWidget(self.btn_filtertoDB)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.text_debug = QtGui.QTextEdit(Form)
        self.text_debug.setObjectName(_fromUtf8("text_debug"))
        self.verticalLayout_6.addWidget(self.text_debug)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.line_2 = QtGui.QFrame(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_2.setFont(font)
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_7.addWidget(self.line_2)
        self.btn_search = QtGui.QPushButton(Form)
        self.btn_search.setText(QtGui.QApplication.translate("Form", "查询界面", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_search.setObjectName(_fromUtf8("btn_search"))
        self.verticalLayout_7.addWidget(self.btn_search)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass

