# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search.ui'
#
# Created: Mon Oct 24 11:31:23 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class searchUi(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1369, 708)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "查询界面", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_2 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_6 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TeXGyreBonum"))
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setText(QtGui.QApplication.translate("Form", "数据库查询", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_13 = QtGui.QLabel(Form)
        self.label_13.setText(QtGui.QApplication.translate("Form", "源端口", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_9.addWidget(self.label_13)
        self.lineEdit_srcPort = QtGui.QLineEdit(Form)
        self.lineEdit_srcPort.setObjectName(_fromUtf8("lineEdit_srcPort"))
        self.horizontalLayout_9.addWidget(self.lineEdit_srcPort)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_14 = QtGui.QLabel(Form)
        self.label_14.setText(QtGui.QApplication.translate("Form", "目端口", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_10.addWidget(self.label_14)
        self.lineEdit_destPort = QtGui.QLineEdit(Form)
        self.lineEdit_destPort.setObjectName(_fromUtf8("lineEdit_destPort"))
        self.horizontalLayout_10.addWidget(self.lineEdit_destPort)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_17.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_15 = QtGui.QLabel(Form)
        self.label_15.setText(QtGui.QApplication.translate("Form", "源IP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_11.addWidget(self.label_15)
        self.lineEdit_srcIP = QtGui.QLineEdit(Form)
        self.lineEdit_srcIP.setObjectName(_fromUtf8("lineEdit_srcIP"))
        self.horizontalLayout_11.addWidget(self.lineEdit_srcIP)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_16 = QtGui.QLabel(Form)
        self.label_16.setText(QtGui.QApplication.translate("Form", "目IP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_12.addWidget(self.label_16)
        self.lineEdit_destIP = QtGui.QLineEdit(Form)
        self.lineEdit_destIP.setObjectName(_fromUtf8("lineEdit_destIP"))
        self.horizontalLayout_12.addWidget(self.lineEdit_destIP)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_17.addLayout(self.verticalLayout_8)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_17 = QtGui.QLabel(Form)
        self.label_17.setText(QtGui.QApplication.translate("Form", "关键字", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_13.addWidget(self.label_17)
        self.lineEdit_KeyWordDB = QtGui.QLineEdit(Form)
        self.lineEdit_KeyWordDB.setObjectName(_fromUtf8("lineEdit_KeyWordDB"))
        self.horizontalLayout_13.addWidget(self.lineEdit_KeyWordDB)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_18 = QtGui.QLabel(Form)
        self.label_18.setText(QtGui.QApplication.translate("Form", "协议", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_14.addWidget(self.label_18)
        self.lineEdit_protocol = QtGui.QLineEdit(Form)
        self.lineEdit_protocol.setObjectName(_fromUtf8("lineEdit_protocol"))
        self.horizontalLayout_14.addWidget(self.lineEdit_protocol)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_17.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.btn_connectDB = QtGui.QPushButton(Form)
        self.btn_connectDB.setText(QtGui.QApplication.translate("Form", "连接数据库", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_connectDB.setObjectName(_fromUtf8("btn_connectDB"))
        self.verticalLayout_9.addWidget(self.btn_connectDB)
        self.btn_clear = QtGui.QPushButton(Form)
        self.btn_clear.setText(QtGui.QApplication.translate("Form", "清空", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clear.setObjectName(_fromUtf8("btn_clear"))
        self.verticalLayout_9.addWidget(self.btn_clear)
        self.btn_search = QtGui.QPushButton(Form)
        self.btn_search.setText(QtGui.QApplication.translate("Form", "查询", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_search.setObjectName(_fromUtf8("btn_search"))
        self.verticalLayout_9.addWidget(self.btn_search)
        self.horizontalLayout_17.addLayout(self.verticalLayout_9)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.line_3 = QtGui.QFrame(Form)
        self.line_3.setFrameShadow(QtGui.QFrame.Plain)
        self.line_3.setLineWidth(3)
        self.line_3.setMidLineWidth(1)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.tableView_DB = QtGui.QTableView(Form)
        self.tableView_DB.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableView_DB.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableView_DB.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableView_DB.setSortingEnabled(True)
        self.tableView_DB.setObjectName(_fromUtf8("tableView_DB"))
        self.verticalLayout.addWidget(self.tableView_DB)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass

